service:
  name: web-service
  port: 8080
  tags: ['web', 'default']
consul:
  host: 106.12.173.182
  port: 8500
  check:
    protocol: http
    route: /
    interval: 30s
    timeout: 3s
    maxRetry: 5
    retryInterval: 5s
    deregisterCriticalServiceAfter: 60m
