service:
  name: base-service
  port: 3001
  tags: ['api']
consul:
  host: 106.12.173.182
  port: 8500
  check:
    protocol: http
    route: /health
    interval: 30s
    timeout: 3s
    maxRetry: 5
    retryInterval: 5s
    deregisterCriticalServiceAfter: 60m
